package com.example.order.model;

public enum OrderEvent {
    ORDER_CREATED,
    CREDIT_CARD_AUTHORIZED,
    CREDIT_CARD_AUTHORIZATION_FAILED,
    TICKET_CREATED,
    TICKET_CREATION_FAILED,
    CREDIT_CARD_CHARGED,
    PAYMENT_FAILED,
    MANUFACTURED,
    DELIVERED,
    DELIVERY_FAILED,
    ORDER_CANCELED
}
