package com.example.order.model;

public enum OrderState {
    CREATED,
    APPROVAL_PENDING,
    CREDIT_CARD_AUTHORIZED,
    CREDIT_CARD_AUTHORIZATION_FAILED,
    TICKET_CREATED,
    TICKET_CREATION_FAILED,
    ORDER_PAYED,
    PAYMENT_FAILED,
    MANUFACTURED,
    DELIVERED,
    DELIVERY_FAILED,
    ORDER_REJECTED,
    ORDER_CANCELED
}
