server:
  port: 9901
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database: postgresql
  datasource:
    url: ${DB_URL:jdbc:postgresql://order-postgres:5432/order}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    out-of-order: true

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbit-mq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        default-requeue-rejected: false