apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq
  labels:
    name: rabbitmq-service
    app: order-app
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    name: rabbitmq-pod
    app: order-app